services:

  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_gpu
    restart: unless-stopped
    volumes:
      - ./models/model-best:/app/model:ro
    environment:
      - FASTAPI_ROOT_PATH=/bert-api/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  proxy:
    image: nginx
    restart: unless-stopped
    depends_on:
      - api
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80

