services:

  api:
    build: .
    restart: unless-stopped
    volumes:
      - ./models/model-best:/app/model:ro
    environment:
      - FASTAPI_ROOT_PATH=/bert-api/

  proxy:
    image: nginx
    restart: unless-stopped
    depends_on:
      - api
    volumes:
      - ./compose/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80

